# @format

version: "3"

services:
  db:
    image: mysql:5.7
    volumes:
      - ./db/mysql:/var/lib/mysql
    restart: always
    env_file: .env

  drupal:
    image: drupal:latest
    volumes:
      - ./drupal/themes:/var/www/html/themes
      - ./drupal/modules:/var/www/html/modules
      - ./drupal/profiles:/var/www/html/profiles
      - ./drupal/sites/default/files:/var/www/html/sites/default/files
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./config:/opt/drupal/config
      - ./composer.json:/opt/drupal/composer.json
      - ./composer.lock:/opt/drupal/composer.lock
    ports:
      - 2020:80
    depends_on:
      - db
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    env_file: .env
    depends_on:
      - db
    ports:
      - 2222:80

volumes:
  data: {}

